version: '2'

services:
    nginx:
        build:
            context: ./nginx
        volumes:
            - ..:/usr/share/nginx/html
            - ../var/log:/var/log
            - ./nginx/root_home:/root
        ports:
            - "80:80"
        stdin_open: true
        tty: true
        networks:
            backend:
                aliases:
                    - cfwheels145tutorials.frontend

    lucee:
        build:
            context: ./lucee
            args:
                - LUCEE_PASSWORD=${LUCEE_PASSWORD}
        volumes:
            - ..:/var/www
            - ../var/log/tomcat:/usr/local/tomcat/log
            - ../var/log/lucee:/opt/lucee/web/logs
            - ./lucee/root_home:/root
        ports:
            - "8888:8888"
        stdin_open: true
        tty: true
        networks:
            backend:
                aliases:
                    - cfwheels145tutorials.lucee

    mysql:
        build:
            context: ./mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysqlData:/var/lib/mysql
            - ./mysql/root_home:/root
            - ../var/log:/var/log
        stdin_open: true
        tty: true
        networks:
            backend:
                aliases:
                    - database.backend

volumes:
    mysqlData:

networks:
    backend:
        driver: "bridge"
